import logging

from fastapi import APIRouter, File, UploadFile, status

from app.schemas.transcription import TranscriptionResponse
from app.services.transcription_service import transcription_service

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/transcribe", tags=["Transcription"])


@router.post(
    "",
    response_model=TranscriptionResponse,
    status_code=status.HTTP_200_OK,
    summary="Transcribe lecture audio",
    description="Uploads a lecture audio file and returns a text transcript generated by Whisper.",
)
async def transcribe_audio(audio_file: UploadFile = File(..., description="Lecture audio file (mp3, wav, m4a, etc.)")):
    logger.info("Received transcription request for file: %s", audio_file.filename)
    result = await transcription_service.transcribe(audio_file)
    return TranscriptionResponse(**result)
